### ISSUE TITLE
Support use as pipeline material

### ISSUE THREAD

**Issue by kaazoo** [gocd/docker-registry-artifact-plugin#136]
I would like to use the plugin also for pipelines materials. Trigger pipelines based on Docker images changes (e.g. new tag).
Is it possible to add support for that or is that out of scope of the project?

**Comment by arvindsv** [comment]
I think that's out of scope for _this_ plugin. Two options I see are:

1. If you're using this plugin to publish a Docker image as an artifact, then you can use the pipeline this plugin is used itself as a material.

2. If you're not using this plugin, then an SCM poller plugin like https://github.com/magnus-lycka/gocd-docker-poller might be what you're looking for.

I'll close this for now. But, conversations can continue and this can be reopened if needed. :)
