### ISSUE TITLE
Support for private registry

### ISSUE THREAD

**Issue by grawert** [gocd/docker-registry-artifact-plugin#137]
I was trying to use the plugin with a private registry. The registry is using API v2. It seems the plugin is not supporting it. I am getting the following error message. Credentials are correct, though.
```
java.lang.RuntimeException: unauthorized: incorrect username or password".
```
Is there any plan to support registry v2?

**Comment by grawert** [comment]
The plugin is working with registry v2. The error message refers to Docker trying to push to Dockerhub registry, instead of the private registry, given as registryUrl parameter.

This is reflected by the debug logs:
`POST /images/dashboard/backend/push?tag=52-1b919e2 HTTP/1.1[\r][\n]`
`{"status":"The push refers to repository [docker.io/dashboard/backend]"}[\r][\n]`

The image name in the push command does not include the registry url. Therefore Docker assumes the default registry.
https://github.com/gocd/docker-registry-artifact-plugin/blob/master/src/main/java/cd/go/artifact/docker/registry/executors/PublishArtifactExecutor.java#L66

**Comment by varshavaradarajan** [comment]
Thanks for confirming @grawert! 
Related: #21

**Comment by grawert** [comment]
@varshavaradarajan: Thanks for the hint! This one is a little hard to catch. I added a note to the README.md in #140.
