### ISSUE TITLE
Plugin not working with ECR.

### ISSUE THREAD

**Issue by shivani-hotstar** [gocd/docker-registry-artifact-plugin#141]
I have configured plugin for RegistryType : ecr.

and i am using https://github.com/gocd/docker-registry-artifact-plugin/releases/download/v1.1.0-110-exp/docker-registry-artifact-plugin-1.1.0-110.jar

i have a dockerfile in my github repo and building the dockerimage here in this place itself but then i am getting confused what to fill under External artifact step :--
Image:
Tag Pattern:
Build File:

and i am facing below error :--
[go] The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to publish Artifact[id=ecr_id, storeId=ecr_dev, artifactPlanConfig={"Image":"docker tag test_dev:latest xyz/test_dev:latest","Tag":"latest"}]: Request error: POST unix://localhost:80/images/docker%20tag%20test_dev:latest%xyz/test_dev:latest/push?tag=latest: 500, body: {"message":"invalid reference format"}

**Comment by varshavaradarajan** [comment]
Image field can't be a command.

Image: xyz/test_dev
Tag: latest (usually should be a version or something that changes for every pipeline run, but latest works too if you know what you're doing)

**Comment by shivani-hotstar** [comment]
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
test_dev                                                 latest              e8fd92fcaed4        6 days ago          32.2 MB

This is what i am building on gocd agent and now i want to push this image to my ecr repo .

I tried giving Image: test_dev
but failed with same error.

**Comment by varshavaradarajan** [comment]
You need to do the docker tag step after building the image. So that you get xyz/test_dev. Not provide it as part of the image field.  docker build and docker tag commands must be part of the task.

**Comment by shivani-hotstar** [comment]
hey yes i think that issue is resolved now but now i am facing this wired issue .
[go] The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to publish Artifact[id=ecr, storeId=ecr_id, artifactPlanConfig={"Image":"test_dev","Tag":"latest"}]: java.lang.RuntimeException: unauthorized: incorrect username or password'

so when we configure the artifact store they don't give option to add username and password for ECR and now they giving  (unauthorized: incorrect username or password').

**Comment by varshavaradarajan** [comment]
When pushing to a container registry, the image should be username/image, you have built the image as test_dev, build it as xyz/test_dev and specify xyz/test_dev for the image field. 

Please take a look at the documentation - https://docs.gocd.org/current/gocd_on_kubernetes/sample_pipelines_explained.html

**Comment by shivani-hotstar** [comment]
format_version: 3
pipelines:
  build_and_publish_image:
    group: Infrastructure
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: git@abc
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          job1:
            timeout: 0
            elastic_profile_id: 123-infra
            artifacts:
            - external:
                id: ecr
                store_id: ecr_id
                configuration:
                  options:
                    BuildFile: ''
                    Tag: ''
                    Image: docker tag  xyz/test_dev
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: '1'
                options:
                  script: "docker build -t xyz/test_dev\
                    \ .\r\n\r\ndocker tag  xyz/test_dev\
                    \   xyz/test_dev:latest"
                  shtype: bash
                run_if: passed

Here: xyz is my AWS ECR repo 

Error :-- [go] The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to publish Artifact[id=ecr, storeId=ecr_id, artifactPlanConfig={"Image":"docker tag  xyz/test_dev","Tag":"latest"}]: Request error: POST unix://localhost:80/images/docker%20tag%20%20xyz/test_dev/push?tag=latest: 500, body: {"message":"invalid reference format"}
