### ISSUE TITLE
Plugin issue with AWS ecr repo

### ISSUE THREAD

**Issue by shivani-hotstar** [gocd/docker-registry-artifact-plugin#142]
format_version: 3
pipelines:
  build_and_publish_image:
    group: Infrastructure
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: git@abc
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          job1:
            timeout: 0
            elastic_profile_id: 123-infra
            artifacts:
            - external:
                id: ecr
                store_id: ecr_id
                configuration:
                  options:
                    BuildFile: ''
                    Tag: ''
                    Image: docker tag  xyz/test_dev
            tasks:
            - plugin:
                configuration:
                  id: script-executor
                  version: '1'
                options:
                  script: "docker build -t xyz/test_dev\
                    \ .\r\n\r\ndocker tag  xyz/test_dev\
                    \   xyz/test_dev:latest"
                  shtype: bash
                run_if: passed

Here: xyz is my AWS ECR repo 

Error :-- [go] The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to publish Artifact[id=ecr, storeId=ecr_id, artifactPlanConfig={"Image":"docker tag  xyz/test_dev","Tag":"latest"}]: Request error: POST unix://localhost:80/images/docker%20tag%20%20xyz/test_dev/push?tag=latest: 500, body: {"message":"invalid reference format"}

_Originally posted by @shivani-hotstar in https://github.com/gocd/docker-registry-artifact-plugin/issues/141#issuecomment-546235918_

**Comment by arvindsv** [comment]
As mentioned in #141, all of this seems to be wrong configuration passed to the plugin and not a problem with the plugin itself. Please don't open new issues for the same problem. It just clutters the issues page. I'm closing this for now, since this is _not_ a plugin issue. It has been tested with ECR.

Please take a look at the: "Image:" line and see if it makes sense.

**Comment by shivani-hotstar** [comment]
@arvindsv yes that's possible that this is not a plugin issue but i didn't find any updated doc as well for the AWS ecr repo .
not a single explanation about above configuration.
i am expecting solution from you guys .
