### ISSUE TITLE
Permission denied error when experimenting with push to a private registry

### ISSUE THREAD

**Issue by dwyart** [gocd/docker-registry-artifact-plugin#21]
Hi,

Currently working on the implementation of a private Docker registry, and using GOCD, I was glad to see that version 18.7 was adding support for registry.

I followed the guidelines in the README and I think the info for my registry (URL and credentials) are correct but when trying to push from a task, I get this error : 

[go] Interaction with plugin with id 'cd.go.artifact.docker.registry' implementing 'artifact' extension failed while requesting for 'cd.go.artifact.publish-artifact'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to publish Artifact[id=back-dist, storeId=padoa_docker_registry, artifactPlanConfig={"Image":"padoa/back-dist","Tag":"${GO_PIPELINE_LABEL}"}]: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied']

I did not find more details in the gocd logs, so I am a bit stuck.

Could you provide some hints on how to debug things further? Of course I could work with explicit docker push commands in my tasks, but using the plugin seems cleaner to me, so I would be glad to have it working.

gocd is running as go but go is member of the docker group, so I do not think the issue is in that area.

Many thanks in advance!

**Comment by dwyart** [comment]
After further thinking, I realized that I use dockerized gocd agents, so I will investigate further there, but I think the agents do not have everything that is needed to interact with the registry.

**Comment by dwyart** [comment]
After further research, I have added to SSL cert to docker agents (to be able to access the registry in HTTPS) ; I also found the logs, but not being a Java expert it is impossible for me to interpret these 100s of lines revolving around "Permission denied". I did not really find more details and the Java docker client is hiding the upper chain of errors...

Any suggestion on how to make progress or investigate further will be much appreciated!

Thanks

Damien

**Comment by akshaydewan** [comment]
Hi Damien,

Here's how I was debugging the plugin while working on it (I use IntelliJ IDE) - 
When building the plugin jar, make sure to include the source files. There are some commented lines in [build.gradle](https://github.com/gocd/docker-registry-artifact-plugin/blob/master/build.gradle#L118) that should do this. 

Copy the jar to the GoCD server, and run it in debug mode [from the IDE](https://developer.gocd.org/current/2/2.1.html). You can then search for the plugin files in the server's project, and add breakpoints. When the plugin executes a publish task, your breakpoint should be hit. And if I'm not mistaken, for the breakpoint to work, the Agent should also be running in debug mode from the IDE, because the publish task is performed in the Agent's context.

Hope this helps.

**Comment by asnir** [comment]
@dwyart any progress?

**Comment by dwyart** [comment]
Hi! Thanks for asking!

Holidays did not help to make real progress, but a colleague has now jumped in, so we are two to perform further tests since a few days.

It seems that using the gocd-agent dind image is helping (we were building our own custom dind image), but we are not sure why, so still lookign at it. But we definitively see some runs work OK with the plugin, so this is quite good news. 

During my first tests, I might also have screwed up with tags, right now we are careful to include to full registry name in the tag and this might also have helped.

We will keep you informed if we can get to more precise conclusions.

Thanks again!

**Comment by asnir** [comment]
Did it work for a public repo?

**Comment by dwyart** [comment]
This is a private setup, so we did not test a public repo at all.

**Comment by wittenbergio** [comment]
Hi @dwyart . I seem to be running into the same problem, trying to push images to a private repository in nexus, using username/password. Have you figured it out? It's seems strange to me that it works with the public dockerhub repository but not with a private one. I would have guessed it's the same protocol, just a different "backend" to store the images.

**Comment by dwyart** [comment]
Hi, it now working but our setup is a bit different, our registry is managed by k8s. Still not 100% sure what made the plugin work, but we have no problem anymore.

Make sure you specify the full URL of the registry and image (including tags).

**Comment by wittenbergio** [comment]
@dwyart thanks, this helped. I figured that the gocd docs only consider the official docker registry. As you say, if you put the whole repo/name:tag in the Artifact tab it works.

**Comment by arvindsv** [comment]
Hello! Based on these comments, I will close this issue. Please let me know if I shouldn't (and should reopen it).

If you think that the documentation should be improved, please open a pull request for it. It will be appreciated. Thank you so much!
