### ISSUE TITLE
Support for Quay.io registry

### ISSUE THREAD

**Issue by tuxpower** [gocd/docker-registry-artifact-plugin#23]
Any idea if [Quay.io](https://quay.io/) registry is supported and how can this be configured?

**Comment by arvindsv** [comment]
Looks like it is a proper docker registry. Should work.

You might want to see if the registry URL is: https://quay.io/v1/ and might want to use an [access token](https://docs.quay.io/glossary/access-token.html).

Doing a: `docker login quay.io` and then seeing what it puts into `~/.docker/config.json` might be useful. For instance, docker hub login ends up adding something like:

```
"auths" : {
  "https://index.docker.io/v1/" : {
  }
}
```

... which helps to find out the registry URL to use.

**Comment by varshavaradarajan** [comment]
Once you have an account, you can generated a password for the CLI. Using the registry url as `https://quay.io`, pushing `quay.io/username/image:tag` is possible. 

This issue can be closed.

**Comment by arpad9** [comment]
@tuxpower Did you figure this out?  I can't get this to go no matter what combination of url and auth I use.

**Comment by varshavaradarajan** [comment]
@arpad9 - these are the steps I followed to successfully push a docker image to quay

- Go to the account settings in quay, generate a cli password and copy it
- Configure the artifact store as shown
<img width="1050" alt="Screen Shot 2019-04-03 at 2 47 48 PM" src="https://user-images.githubusercontent.com/4715748/55515643-ea83ec80-561f-11e9-90b3-38c193234f7f.png">
- Navigate to pipeline->stage->job->artifact, configure artifact to publish as shown
<img width="811" alt="Screen Shot 2019-04-03 at 2 50 23 PM" src="https://user-images.githubusercontent.com/4715748/55515707-10a98c80-5620-11e9-850e-9d93efd0d443.png">

Image: quay.io/username/repo-name

- Run the pipeline. The plugin shows the pushing in progress.
Once the job completes, quay has the tag
<img width="1412" alt="Screen Shot 2019-04-03 at 2 53 53 PM" src="https://user-images.githubusercontent.com/4715748/55515836-7269f680-5620-11e9-84e7-ec52df1bb8fd.png">

**Comment by arpad9** [comment]
Yes, thank you!  Qualifying the image with the registry (quay.io/username/repo-name) during the build was the key otherwise the Artifact config wouldn't find the image locally to push.  Now it works.
