### ISSUE TITLE
Can't load the plugin on goCD 18.10.0

### ISSUE THREAD

**Issue by pavelkostyurin** [gocd/docker-registry-artifact-plugin#28]
Hi there!

I can't get it up and running on goCD 18.10.0 (7703-42d1cbe661161b5400289ead86c0447c84af8c0a).
Any prerequisites to make it work?

Plugin file location
/var/lib/go-server/plugins/external/docker-registry-artifact-plugin-1.0.0-66.jar
BundledNo
Target Go Version18.7.0
There were errors loading the pluginInteraction with plugin with id 'cd.go.artifact.docker.registry' implementing 'artifact' extension failed while requesting for 'cd.go.artifact.store.get-metadata'. Reason: [Could not find matching extension version between Plugin[cd.go.artifact.docker.registry] and Go]

**Comment by GaneshSPatil** [comment]
Hello @pavelkostyurin,

Thanks for reporting the issue. 

From the logs, we could see that the version of the `docker-registry-artifact-plugin` you're using is `1.0.0-66 `. Whereas, the latest available plugin version is `1.0.0-25`.

Please provide the following information about the `docker-registry-artifact-plugin` that you're using:
1. Plugin Id.
2. Plugin Version.
3. The location from where you've downloaded the plugin.

The above mentioned information will help us debug this issue further.

**Comment by pavelkostyurin** [comment]
Thanks for the quick response.

I built jar with version 1.0.0-66 from the source code, using instructions, provided in README: ./gradlew clean test assemble

I also tried with release version 1.0.0.-25 - same result.

Plugin id in both cases is the same: cd.go.artifact.docker.registry

**Comment by GaneshSPatil** [comment]
Hello @pavelkostyurin,

Thanks for confirming.

The latest available plugin `v1.0.0.-25` is built from the master and contains the commit https://github.com/gocd/docker-registry-artifact-plugin/commit/1c6595f7116cdf1c49f94dcaaf5fc8d6cda9ca51. 
We've changed the plugin-api contract versions as part of the mentioned commit, which has caused the incompatibility with GoCD server.

As of now, we request you to downgrade your plugin to use [`v1.0.0`](https://github.com/gocd/docker-registry-artifact-plugin/releases/tag/1.0.0), so that it works with `v18.10.0` of GoCD.

We're working on fixing the plugin compatibility issue with the server and will update this issue with our findings.

**Comment by pavelkostyurin** [comment]
Thanks for your help, 1.0.0-3 started up successfully.

**Comment by arvindsv** [comment]
@GaneshSPatil This change was made for https://github.com/gocd/docker-registry-artifact-plugin/pull/22 combined with https://github.com/gocd/gocd/pull/5188. So, there was a new version needed on the server side (`2.0`). Given that the feature is useful, I don't see any way to fix the plugin compatibility. Unless we want the plugin to somehow support both versions, which might not be possible.

I think we should update the target version of that plugin to notify that it needs a newer version. Do you see any other approach?

/cc @varshavaradarajan

**Comment by arvindsv** [comment]
`GoPluginIdentifier` does support providing multiple versions in `supportedExtensionVersions`, but I don't know how a new plugin with old GoCD server will work.

**Comment by arvindsv** [comment]
I updated the [release's name](https://github.com/gocd/docker-registry-artifact-plugin/releases/tag/1.0.0-25) with the version of GoCD needed. But, we should update the [target version](https://github.com/gocd/docker-registry-artifact-plugin/blob/b03637b7757a8033056c7928761df191c950d079/build.gradle#L36) too.
