### ISSUE TITLE
Error Pushing to ECR

### ISSUE THREAD

**Issue by m13t** [gocd/docker-registry-artifact-plugin#50]
Hi,

I'm seeing a problem when trying to push an image to ECR:

```
cd.go.artifact.docker.registry] Failed to publish Artifact[id=container, storeId=ecr, artifactPlanConfig={"Image":"test/image","Tag":"${GO_PIPELINE_LABEL}"}]: java.lang.IllegalArgumentException: Expected authority at index 7: http://
[go] Interaction with plugin with id 'cd.go.artifact.docker.registry' implementing 'artifact' extension failed while requesting for 'cd.go.artifact.publish-artifact'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to publish Artifact[id=container, storeId=ecr, artifactPlanConfig={"Image":"test/image","Tag":"${GO_PIPELINE_LABEL}"}]: Expected authority at index 7: http://']
```

The artifact store is configured without AWS credentials set as container the GoCD Server and Agents are running in have roles associated allowing them to push to ECR.

**Comment by varshavaradarajan** [comment]
@m13t - Shouldn't the image have the registry id? Because the docker client needs to know how to push it. So, the configuration for the image , if I am pushing to ECR will be something like `123456.dkr.ecr.us-west-1.amazonaws.com/namespace/image`.

**Comment by m13t** [comment]
I agree the documentation is rather sparse about the specifics of setting it up. However, that part is set under the configuration of the actual artifact store rather than in the `publish artifact` step. As per the [image](https://github.com/gocd/docker-registry-artifact-plugin/blob/master/images/artifact_store_ecr.png) in the readme.

**Comment by varshavaradarajan** [comment]
@m13t - you'd need to specify at the publish artifact level too. Yes, the doc could be clearer about it. The reason for specifying the registry id at the store level is to obtain the right token before being able to push the image. Its to provide an option to push to registries other than the default. 

Mind submitting a PR to update the doc?

**Comment by m13t** [comment]
@varshavaradarajan ah okay. That seems like an oversight a bit as it now means we need to store the registry in our config files as well rather than being able to keep them free of a particular repository address.

Our use case requires us to have multiple repositories for each image (production and non-production). The hope with the plugin was that by specifying the repository ID in the GoCD config, it nicely decouples this away from the job specifics.

Does that not seem like a logical thing to have, especially given that the registry ID is specified at config time anyway, and that specifying any other registry ID at artifact publish time wouldn't work anyway if the temporary AWS credentials are specific to the account specified in the config?

**Comment by m13t** [comment]
Just had a quick check with using the domain part of the image name and that does work. It's not ideal but we could possibly assign the job to an environment and have a variable assigned to the environment and reference that in the artifact push so that it's not kept in the pipeline spec.

However, I tried pushing to a nonexistent ECR repository and it marked the job as successful with no errors, warnings or any output.

**Comment by varshavaradarajan** [comment]
>  tried pushing to a nonexistent ECR repository and it marked the job as successful with no errors, warnings or any output.

Oh, will need to try again. When I was trying to push to nonexistent repo a while back, the error was `name unknown: The repository with name 'non-existent' does not exist in the registry with id '...'` as mentioned in https://github.com/gocd/docker-registry-artifact-plugin/issues/9#issuecomment-451600209. Will try it out and update here. Thank you!

**Comment by varshavaradarajan** [comment]
@m13t - the job fails with an error from the docker registry artifact plugin if the ecr repo does not exist - 
<img width="1340" alt="Screen Shot 2019-04-12 at 2 52 00 PM" src="https://user-images.githubusercontent.com/4715748/56068159-a933c100-5d32-11e9-9ff7-b816bc535434.png">
